name: pr dev 2 build
on:
  schedule:
    - cron: '6 21 * * *'
  workflow_dispatch:
jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create pull request
        run: gh pr create -B build -H dev --title 'Auto pr dev into build' --body 'Automatically created by gh-actions.'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_OPTECHX }}

  triage:
    needs: [ "auto-pr" ]
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GH_TOKEN_OPTECHX }}"
  
  auto-merge:
    needs: [ "triage" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: merge pull request
        run: gh pr merge --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_OPTECHX }}
