name: dev Special Run
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  special:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Developer Tools
        shell: pwsh
        run: ./lib/tranches/developer-tools.ps1
        env:
          ENGINE_API_URI: ${{ secrets.ENGINE_API_URI_DEV }}

      - name: Education
        shell: pwsh
        run: ./lib/tranches/education.ps1
        env:
          ENGINE_API_URI: ${{ secrets.ENGINE_API_URI_DEV }}

      - name: Entertainment
        shell: pwsh
        run: ./lib/tranches/entertainment.ps1
        env:
          ENGINE_API_URI: ${{ secrets.ENGINE_API_URI_DEV }}

      - name: Games
        shell: pwsh
        run: ./lib/tranches/games.ps1
        env:
          ENGINE_API_URI: ${{ secrets.ENGINE_API_URI_DEV }}

      - name: Internet
        shell: pwsh
        run: ./lib/tranches/internet.ps1
        env:
          ENGINE_API_URI: ${{ secrets.ENGINE_API_URI_DEV }}

      - name: Lifestyle
        shell: pwsh
        run: ./lib/tranches/lifestyle.ps1
        env:
          ENGINE_API_URI: ${{ secrets.ENGINE_API_URI_DEV }}

      - name: Photo Design
        shell: pwsh
        run: ./lib/tranches/photo-design.ps1
        env:
          ENGINE_API_URI: ${{ secrets.ENGINE_API_URI_DEV }}


