name: Clear old gh actions
on:
  schedule:
    - cron: '5 22 * * *'
  workflow_dispatch:
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          user=OptechX
          repo=library.apps.images
          gh api repos/$user/$repo/actions/runs \
          --paginate -q '.workflow_runs[] | select(.head_branch != "master") | "\(.id)"' | \
          xargs -n1 -I % gh api --silent repos/$user/$repo/actions/runs/% -X DELETE
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}